sms.provider=mock
sms.notifylk.user-id=${SMS_NOTIFYLK_USER_ID}
sms.notifylk.api-key=${SMS_NOTIFYLK_API_KEY}
sms.notifylk.sender-id=${SMS_NOTIFYLK_SENDER_ID}
payhere.merchant-id=${PAYHERE_MERCHANT_ID}
payhere.secret=${PAYHERE_MERCHANT_SECRET}
payhere.sandbox=true
payhere.notify-url=https://shiny-sites-hide.loca.lt/api/payments/notify
payhere.return-url=http://localhost:5173/payment-success
payhere.cancel-url=http://localhost:5173/payment-cancel